# Generated by Django 4.2.4 on 2023-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
