# Generated by Django 4.2.4 on 2023-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0004_userprofile_bio_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
