# Generated by Django 4.2.4 on 2023-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0006_userprofile_notes_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=20)),
                ('not_icerik', models.TextField()),
            ],
        ),
    ]
