# Generated by Django 4.2.4 on 2023-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0007_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='not',
            name='gun',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
