# Generated by Django 4.2.4 on 2023-08-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0008_alter_not_gun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Not',
        ),
    ]
