# Generated by Django 4.2.4 on 2023-08-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takipsistemi', '0012_alter_friend_friend_alter_friend_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='accepted',
            new_name='is_accepted',
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='created_at',
        ),
    ]
