# Generated by Django 4.2.4 on 2023-08-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0013_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={'verbose_name_plural': 'Friendship Requests'},
        ),
    ]
