# Generated by Django 4.2.4 on 2023-08-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0014_alter_friendshiprequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={},
        ),
    ]
