# Generated by Django 4.2.4 on 2023-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0017_alter_friendshiprequest_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
