# Generated by Django 4.2.4 on 2023-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0020_etkinlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(max_length=100)),
                ('proje_sahibi', models.CharField(max_length=100)),
                ('proje_amaci', models.TextField()),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
            ],
        ),
    ]
