# Generated by Django 4.2.4 on 2023-09-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0021_proje'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttSema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gantt_data', models.JSONField()),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takipsistemi.proje')),
            ],
        ),
    ]
