# Generated by Django 4.2.5 on 2023-09-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0024_chat_title_alter_chat_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takipsistemi.chat'),
        ),
    ]
