# Generated by Django 4.2.5 on 2023-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0025_remove_message_media_file_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='description',
            field=models.TextField(),
        ),
    ]
