# Generated by Django 4.2.5 on 2023-09-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0026_alter_etkinlik_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
