# Generated by Django 4.2.5 on 2023-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0029_remove_message_media_file_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='message_media/'),
        ),
    ]
