# Generated by Django 4.2.5 on 2023-09-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0031_alter_chat_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='allocation',
            new_name='adam_ay_orani',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='takipsistemi.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adam_ay_orani',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='takipsistemi.userprofile'),
        ),
    ]
