# Generated by Django 4.2.5 on 2023-09-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipsistemi', '0032_rename_allocation_assignment_adam_ay_orani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_adam_ay',
            field=models.FloatField(default=1.0),
        ),
    ]
